import json
import shutil
from pathlib import Path

from ..contract import sha256_file
from .acquisition import ensure_sound

MAX_REQUIREMENTS = 32
MAX_QUERY_VARIANTS = 6
MAX_DISCOVERY_LIMIT = 24


def _load_json(path):
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"JSON object required: {path}")
    return data


def _validate_requirements(data):
    if data.get("version") != 1:
        raise ValueError("Sound requirements version must be 1")
    items = data.get("sounds")
    if not isinstance(items, list):
        raise ValueError("Sound requirements sounds must be an array")
    if len(items) > MAX_REQUIREMENTS:
        raise ValueError(f"Sound requirements are limited to {MAX_REQUIREMENTS} entries")
    ids = []
    for index, item in enumerate(items, start=1):
        label = f"sounds[{index}]"
        if not isinstance(item, dict):
            raise ValueError(f"{label} must be an object")
        sound_id = item.get("id")
        if not isinstance(sound_id, str) or not sound_id.strip():
            raise ValueError(f"{label}.id is required")
        if item.get("type") not in {"ambience", "event"}:
            raise ValueError(f"{label}.type must be ambience or event")
        query = item.get("query")
        if not isinstance(query, str) or not query.strip():
            raise ValueError(f"{label}.query is required")
        for key in ("required_tags", "preferred_tags", "providers"):
            value = item.get(key, [])
            if not isinstance(value, list) or any(not isinstance(v, str) or not v.strip() for v in value):
                raise ValueError(f"{label}.{key} must be an array of non-empty strings")
        ids.append(sound_id)
    if len(ids) != len(set(ids)):
        raise ValueError("Sound requirement ids must be unique")
    return items


def _query_variants(requirement):
    original = " ".join(str(requirement.get("query") or "").split())
    required = [str(value).strip() for value in requirement.get("required_tags", []) if str(value).strip()]
    preferred = [str(value).strip() for value in requirement.get("preferred_tags", []) if str(value).strip()]
    original_tokens = original.split()

    candidates = [
        original,
        " ".join(required + preferred),
        " ".join(required),
    ]
    if len(original_tokens) > 2:
        candidates.extend([
            " ".join(original_tokens[-3:]),
            " ".join(original_tokens[-2:]),
        ])
    candidates.extend(required)

    variants = []
    seen = set()
    for value in candidates:
        normalized = " ".join(value.split()).strip()
        key = normalized.casefold()
        if normalized and key not in seen:
            seen.add(key)
            variants.append(normalized)
        if len(variants) >= MAX_QUERY_VARIANTS:
            break
    return variants


def _candidate_catalogs(seed_dir):
    if not seed_dir:
        return []
    root = Path(seed_dir)
    if not root.exists():
        return []
    result = list(root.rglob("*.catalog.json"))
    result.extend(path for path in root.rglob("sounds.json") if path not in result)
    return sorted(set(result))


def _find_seed_entry(sound_id, sound_type, seed_dir):
    root = Path(seed_dir) if seed_dir else None
    if not root or not root.exists():
        return None
    for catalog_path in _candidate_catalogs(root):
        try:
            data = _load_json(catalog_path)
        except (ValueError, json.JSONDecodeError):
            continue
        for entry in data.get("entries", []):
            if entry.get("id") != sound_id:
                continue
            if entry.get("type") != sound_type or entry.get("status") != "validated":
                continue
            asset_name = Path(entry.get("asset", {}).get("file", "")).name
            if not asset_name:
                continue
            matches = [path for path in root.rglob(asset_name) if path.is_file()]
            for source in matches:
                if sha256_file(source) == entry.get("content_sha256"):
                    return entry, source
    return None


def _copy_entry(entry, source, output_root):
    assets = output_root / "assets"
    assets.mkdir(parents=True, exist_ok=True)
    suffix = Path(source).suffix.lower()
    target = assets / f"{entry['id']}{suffix}"
    if Path(source).resolve() != target.resolve():
        shutil.copyfile(source, target)
    if sha256_file(target) != entry.get("content_sha256"):
        raise ValueError(f"Hydrated sound {entry['id']} hash mismatch")
    copied = json.loads(json.dumps(entry))
    copied["asset"] = {**copied.get("asset", {}), "file": f"assets/{target.name}", "status": "locked"}
    return copied, target


def _write_catalog(root, entries):
    catalog = {
        "version": 1,
        "description": "Hydrated validated sound library generated by Audio Engine.",
        "policy": {
            "publication": "validated-only",
            "render_network_access": False,
            "hydration": "release-first-then-autonomous-acquisition",
        },
        "entries": entries,
    }
    path = root / "sounds.json"
    path.write_text(json.dumps(catalog, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return path


def hydrate_sound_library(requirements_path, *, output_dir=".sound-library", seed_dir=None):
    requirements_path = Path(requirements_path)
    requirements = _validate_requirements(_load_json(requirements_path))
    root = Path(output_dir)
    root.mkdir(parents=True, exist_ok=True)
    (root / "catalogs").mkdir(parents=True, exist_ok=True)
    (root / "selections").mkdir(parents=True, exist_ok=True)

    entries = []
    resolved = []
    unresolved = []
    network_acquisitions = 0
    restored = 0
    catalog_path = _write_catalog(root, entries)

    for requirement in requirements:
        sound_id = requirement["id"]
        sound_type = requirement["type"]
        seed = _find_seed_entry(sound_id, sound_type, seed_dir)
        result = None
        if seed:
            entry, source = seed
            copied, asset = _copy_entry(entry, source, root)
            entries.append(copied)
            restored += 1
            result = {
                "status": "catalog-hit",
                "decision": "automatic",
                "selected_id": sound_id,
                "selected": copied,
                "network_requests_required": False,
                "materialized": {"asset": str(asset)},
                "hydration_source": "durable-seed",
                "query_attempts": [],
            }
        else:
            base_limit = max(1, int(requirement.get("limit", 8)))
            attempts = []
            for attempt_index, query in enumerate(_query_variants(requirement), start=1):
                attempt_limit = min(MAX_DISCOVERY_LIMIT, base_limit * attempt_index)
                acquisition_dir = root / "acquisitions" / sound_id / f"attempt-{attempt_index:02d}"
                result = ensure_sound(
                    query,
                    sound_type=sound_type,
                    sound_id=sound_id,
                    required_tags=requirement.get("required_tags", []),
                    preferred_tags=requirement.get("preferred_tags", []),
                    providers=requirement.get("providers") or None,
                    output_dir=acquisition_dir,
                    catalog_path=catalog_path,
                    limit=attempt_limit,
                    min_score=float(requirement.get("min_score", 70.0)),
                )
                attempts.append({
                    "query": query,
                    "limit": attempt_limit,
                    "status": result.get("status"),
                    "selected_score": result.get("selected_score"),
                    "qualified_count": result.get("qualified_count"),
                })
                if result.get("status") in {"selected", "catalog-hit"}:
                    break
            if result is None:
                result = {"status": "no-selection", "action": "continue-discovery"}
            result["query_attempts"] = attempts

            if result.get("status") in {"selected", "catalog-hit"}:
                entry = result["selected"]
                if result.get("status") == "selected":
                    source = Path(result["materialized"]["asset"])
                    network_acquisitions += 1
                else:
                    source = root / entry["asset"]["file"]
                copied, asset = _copy_entry(entry, source, root)
                entries.append(copied)
                result["selected"] = copied
                result["materialized"] = {**result.get("materialized", {}), "asset": str(asset)}

        if result.get("status") in {"selected", "catalog-hit"}:
            resolved.append(sound_id)
            one_catalog = {
                "version": 1,
                "description": f"Validated hydrated sound {sound_id}.",
                "policy": {"publication": "validated-only", "render_network_access": False},
                "entries": [next(entry for entry in entries if entry["id"] == sound_id)],
            }
            (root / "catalogs" / f"{sound_id}.catalog.json").write_text(
                json.dumps(one_catalog, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
            )
        else:
            unresolved.append({
                "id": sound_id,
                "status": result.get("status"),
                "action": result.get("action"),
                "query_attempts": result.get("query_attempts", []),
            })

        (root / "selections" / f"{sound_id}.selection.json").write_text(
            json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
        )
        catalog_path = _write_catalog(root, entries)

    summary = {
        "schema_version": 1,
        "status": "success" if not unresolved else "partial",
        "requirements_count": len(requirements),
        "resolved_count": len(resolved),
        "unresolved_count": len(unresolved),
        "restored_count": restored,
        "network_acquisition_count": network_acquisitions,
        "resolved": resolved,
        "unresolved": unresolved,
        "render_catalog": str(catalog_path),
        "decision": "automatic",
    }
    (root / "hydration.json").write_text(json.dumps(summary, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return summary
